apiVersion: v1
kind: Pod
metadata:
  name: my-pod      # name of the pod
  labels:
    app: my-app     # pod's label will be app=my-app

spec:
  initContainers:  
  - name: init-db    # runs before main container starts
    image: busybox
    command: ['sh', '-c', 'echo "Waiting for DB..." && sleep 5']

  containers:
  - name: main-app   # main application container
    image: nginx:1.25
    ports:
    - containerPort: 80

  - name: sidecar-logger  # sidecar container
    image: busybox
    command: ['sh', '-c', 'while true; do echo log; sleep 10; done']

  restartPolicy: Always  # restart policy for the pod
