# HPA for NGINX Deployment file.yaml

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: my-app-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: nginx-deployment # change accordingly to deployment name, line-6 in deployment file
 minReplicas: 4
 maxReplicas: 10
 metrics:
   - type: Resource
     resource:
       name: cpu
       target:
         type: Utilization

         averageUtilization: 50
